server:
  debug: true
  systemname: x_gobase #系统名称
  modulename: thirdapi #模块名称
  dbprefix: x_ #数据库前缀
  snowflakenode: 1 #分布式id生成器节点
  http:
    http:
      port: 4511
  token:
    host: 127.0.0.1
    port: 6379
    db: 0
    password: Ho9mpyeqaILEOfjM
    maxidle: 10 #最大的空闲连接数，表示即使没有redis连接时依然可以保持N个空闲的连接，而不被清除，随时处于待命状态。
    maxactive: 100 #最大的激活连接数，表示同时最多有N个连接
    idletimeout: 60 #最大的空闲连接等待时间，超过此时间后，空闲连接将被关闭
    lifetime: 2592000 #token过期时长
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0
    password: Ho9mpyeqaILEOfjM
    maxidle: 10 #最大的空闲连接数，表示即使没有redis连接时依然可以保持N个空闲的连接，而不被清除，随时处于待命状态。
    maxactive: 100 #最大的激活连接数，表示同时最多有N个连接
    idletimeout: 60 #最大的空闲连接等待时间，超过此时间后，空闲连接将被关闭
  db:
    host: 127.0.0.1
    port: 3106
    user: root
    password: root123
    database: abtest
    connmaxidletime: 20 #最大待机时间
    connmaxlifetime: 25 #连接最长生命周期
    connmaxidle: 10 #最大等待连接数
    connmaxopen: 100 #最大打开连接数

